version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: btc_to_rub_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=btc_to_rub_db
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d btc_to_rub_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always