version: '3.8'
services:
  app:
    build: .
    container_name: btc_to_rub
    depends_on:
      - db
    links:
      - db
    entrypoint: "./wait-for-it.sh db:5432 -- python -m script"

  db:
    image: postgres:latest
    container_name: btc_to_rub_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=btc_to_rub_db
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d btc_to_rub_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always